# dbt_energy - Energy Prediction Pipeline
name: 'dbt_energy'
version: '1.0.0'
config-version: 2

profile: 'dbt_energy'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_energy:
    staging:
      +materialized: view
    marts:
      +materialized: table